/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.DaoEntity;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import javax.persistence.Query;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Client;
import model.Client_;
import model.Facture;
import model.Facturer;
import model.Produit;

/**
 *
 * @author socrates
 */
public class FacturerView extends javax.swing.JFrame {

    /**
     * Creates new form FacturerView
     */
    public Integer codecli = 0;
    public Integer codeprod = 0;
    public FacturerView() {
        initComponents();
        clientComboDataList();
        produitComboDataList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        popupMenu1 = new java.awt.PopupMenu();
        jSlider1 = new javax.swing.JSlider();
        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        clientCombotBox = new javax.swing.JComboBox<>();
        nomClient = new javax.swing.JTextField();
        prenomClient = new javax.swing.JTextField();
        telClient = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addClient = new javax.swing.JToggleButton();
        facturer = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        produitCombobox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        designationProd = new javax.swing.JTextField();
        quantiteProd = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        addProduit = new javax.swing.JToggleButton();
        actualiser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProduitTab = new javax.swing.JTable();
        ajoutProduitTab = new javax.swing.JToggleButton();

        jLabel5.setText("jLabel5");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        popupMenu1.setLabel("popupMenu1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nom");

        jLabel3.setText("Prenom");

        jLabel4.setText("Tel");

        clientCombotBox.setMaximumRowCount(100);
        clientCombotBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientCombotBoxMouseClicked(evt);
            }
        });
        clientCombotBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientCombotBoxActionPerformed(evt);
            }
        });

        nomClient.setEditable(false);
        nomClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomClientActionPerformed(evt);
            }
        });

        prenomClient.setEditable(false);

        telClient.setEditable(false);

        jLabel6.setText("Client");

        addClient.setText("+");
        addClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClientActionPerformed(evt);
            }
        });

        facturer.setText("Facturer");
        facturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturerActionPerformed(evt);
            }
        });

        jLabel7.setText("Produit");

        produitCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produitComboboxActionPerformed(evt);
            }
        });

        jLabel8.setText("Designation");

        designationProd.setEditable(false);
        designationProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designationProdActionPerformed(evt);
            }
        });

        jLabel9.setText("Quantité");

        addProduit.setText("+");
        addProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProduitActionPerformed(evt);
            }
        });

        actualiser.setText("Actualiser");
        actualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualiserActionPerformed(evt);
            }
        });

        listProduitTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codeprod", "Designaton", "Quantité", "Prix unitaire", "Coût"
            }
        ));
        jScrollPane1.setViewportView(listProduitTab);

        ajoutProduitTab.setText("+");
        ajoutProduitTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutProduitTabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prenomClient, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telClient, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(clientCombotBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nomClient, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addComponent(addClient))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(produitCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addProduit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(designationProd, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantiteProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ajoutProduitTab))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(facturer))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(actualiser)))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(produitCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(designationProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantiteProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(addProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajoutProduitTab))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clientCombotBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(addClient))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prenomClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualiser)
                    .addComponent(facturer))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomClientActionPerformed

    private void clientCombotBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientCombotBoxActionPerformed
        System.out.println("combobox");
        int index = clientCombotBox.getSelectedIndex();
       
        System.out.println(clientCombotBox.getItemAt(index));
        String comboItem =clientCombotBox.getItemAt(index);
        if(!comboItem.equals(" "))
        {
            String[] cliInfos = clientCombotBox.getItemAt(index).split(" ");
            System.out.println(cliInfos[0]);
            int numCli = Integer.valueOf(cliInfos[0]);
            System.out.println(numCli);
            getClientById(numCli);
        }else{
            nomClient.setText(" ");
            prenomClient.setText(" ");
            telClient.setText(" ");
            codecli = 0;
        }
        
    }//GEN-LAST:event_clientCombotBoxActionPerformed

    private void addClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClientActionPerformed

        JFrame clientView = new ClientView();
        clientView.setVisible(true);
        clientView.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        clientView.setLocationRelativeTo(null);
        clientView.setTitle("Client");
       
    }//GEN-LAST:event_addClientActionPerformed

    private void designationProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designationProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_designationProdActionPerformed

    private void addProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProduitActionPerformed
       JFrame produitView = new ProduitView();
       produitView.setVisible(true);
       produitView.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
       produitView.setLocationRelativeTo(null);
       produitView.setTitle("Produit");
    }//GEN-LAST:event_addProduitActionPerformed

    private void actualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualiserActionPerformed
  
       clientComboDataList();
       produitComboDataList();
     
    }//GEN-LAST:event_actualiserActionPerformed

    private void clientCombotBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientCombotBoxMouseClicked

        
    }//GEN-LAST:event_clientCombotBoxMouseClicked

    private void produitComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produitComboboxActionPerformed
        int index = produitCombobox.getSelectedIndex();
        String comboItem =produitCombobox.getItemAt(index);
        if(!comboItem.equals(" ")){
            String[] produit = comboItem.split(" ");
            designationProd.setText(produit[1]);
            codeprod = Integer.valueOf(produit[0]);
            
        }else{
            designationProd.setText(" "); 
            codeprod = 0;
        }
            
        
    }//GEN-LAST:event_produitComboboxActionPerformed

    private void facturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturerActionPerformed
       if(codecli != 0 && codeprod != 0){
            DaoEntity dao = new DaoEntity();
            dao.getEmf();
            dao.getEm();
            String str = "SELECT c FROM Client c WHERE c.numclient=?1";
            Query query = dao.getEm().createQuery(str);
            query.setParameter(1,codecli);
            Client client = (Client) query.getSingleResult();
            dao.fermer();
            Facture facture =new Facture();
            facture.setClient(client);
            Date date = new Date();
            facture.setDatefact(date);
            dao.Enregistrer(facture);
            
            //List <Facturer> facturer_v=null;
            int nbreRowTab = listProduitTab.getModel().getRowCount();
            Facturer[] facturer_v = new Facturer[nbreRowTab];
            System.out.println(nbreRowTab);
            for(int i =0; i<nbreRowTab; i++ ){
                int idprod = (Integer)listProduitTab.getModel().getValueAt(i, 0);
                Produit produit = getProduitById(idprod); 
                Facturer facturer_e = new Facturer();
                facturer_e.setFacture(facture);
                facturer_e.setProduit(produit);
                facturer_e.setQtecde((Integer) quantiteProd.getValue());
                facturer_v[i] =facturer_e;
                //facturer_v.add(facturer_e);
                DaoEntity daofact = new DaoEntity();
                daofact.Enregistrer(facturer_e);
            }
       }else{
           JOptionPane.showMessageDialog(null, "Produit ou client non selectionné");
       }
        
        
        
    }//GEN-LAST:event_facturerActionPerformed

    private void ajoutProduitTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutProduitTabActionPerformed
        
        if(codeprod!=0){
            Object qte = quantiteProd.getValue();
            if ((Integer)qte<=0){
                JOptionPane.showMessageDialog(null, "Quantité non valide");
            }else{
                DefaultTableModel model=   (DefaultTableModel) listProduitTab.getModel();
                Object codeProd = codeprod;
                Object designation = designationProd.getText();
                Integer prixUnitaire = getProduitById().getPu();
                Object prixU = prixUnitaire;
                Object cout =(Integer)qte  * prixUnitaire;
                model.addRow(new Object[]{codeProd,designation,qte,prixU,cout});
            }
           
        }
        else
        {
            System.out.println("Aucun client ajouté");
            JOptionPane.showMessageDialog(null, "Aucun produit sélectionné");
        }
        
    }//GEN-LAST:event_ajoutProduitTabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacturerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualiser;
    private javax.swing.JToggleButton addClient;
    private javax.swing.JToggleButton addProduit;
    private javax.swing.JToggleButton ajoutProduitTab;
    private javax.swing.JComboBox<String> clientCombotBox;
    private javax.swing.JTextField designationProd;
    private javax.swing.JButton facturer;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTable listProduitTab;
    private javax.swing.JTextField nomClient;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTextField prenomClient;
    private javax.swing.JComboBox<String> produitCombobox;
    private javax.swing.JSpinner quantiteProd;
    private javax.swing.JTextField telClient;
    // End of variables declaration//GEN-END:variables


    @SuppressWarnings("empty-statement")
    private void clientComboDataList(){
        DefaultComboBoxModel model = (DefaultComboBoxModel) clientCombotBox.getModel();
        model.removeAllElements();
        clientCombotBox.addItem(" ");
        DaoEntity dao = new DaoEntity();
        dao.getEmf();
        dao.getEm(); 
        String str = "SELECT c FROM Client c WHERE c.supp=false ORDER BY c.numclient DESC";
        Query query = dao.getEm().createQuery(str);        
        List <Client> clients =  query.getResultList();
        for (Client cli:clients){
            Object client =cli.getNumclient()+" "+ cli.getNomClient()+" "+cli.getPrenomClient();
            clientCombotBox.addItem((String) client);
        } 
         dao.fermer();
    }
    
    private void produitComboDataList(){
        DefaultComboBoxModel model = (DefaultComboBoxModel) produitCombobox.getModel();
        model.removeAllElements();
        produitCombobox.addItem(" ");
        DaoEntity dao = new DaoEntity();
        dao.getEmf();
        dao.getEm(); 
        String str = "SELECT p FROM Produit p WHERE p.supp=false ORDER BY p.codeprod DESC";
        Query query = dao.getEm().createQuery(str);        
        List <Produit> produits =  query.getResultList();
        for (Produit prod:produits){
            Object produit =prod.getCodeprod()+" "+ prod.getDesignation() ;
            produitCombobox.addItem((String) produit);
        } 
        dao.fermer();
    }
    private void getClientById(int numcli){
        DaoEntity dao = new DaoEntity();
        dao.getEmf();
        dao.getEm();
        
        String str = "SELECT c FROM Client c WHERE c.numclient=?1";
        Query query = dao.getEm().createQuery(str);
        query.setParameter(1,numcli);
        Client client = (Client) query.getSingleResult();
        codecli = client.getNumclient();
        nomClient.setText(client.getNomClient());
        prenomClient.setText(client.getPrenomClient());
        telClient.setText(String.valueOf(client.getTelephone()));
        dao.fermer();
    }
    
    private Produit getProduitById(){
         DaoEntity daoprod = new DaoEntity();
        daoprod.getEmf();
        daoprod.getEm();
        String strprod = "SELECT p FROM Produit p WHERE p.codeprod=?1";
        Query queryprod = daoprod.getEm().createQuery(strprod);
        queryprod.setParameter(1,codeprod);
        Produit produit = (Produit) queryprod.getSingleResult();
        daoprod.fermer();
        return produit;
    }
    
    private Produit getProduitById(int idprod){
         DaoEntity daoprod = new DaoEntity();
        daoprod.getEmf();
        daoprod.getEm();
        String strprod = "SELECT p FROM Produit p WHERE p.codeprod=?1";
        Query queryprod = daoprod.getEm().createQuery(strprod);
        queryprod.setParameter(1,idprod);
        Produit produit = (Produit) queryprod.getSingleResult();
        daoprod.fermer();
        return produit;
    }
}

